apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: promo-evaluator

build:
  artifacts:
  - image: us-central1-docker.pkg.dev/m2c-demo/container/promo-evaluator
    jib:
      type: maven
      args: 
      - --no-transfer-progress
      - -Psync
      - -DskipTests
      fromImage: eclipse-temurin:17-jre
    sync:
      auto: true

manifests:
  rawYaml:
  - cloud-run/promo-evaluator.yml

deploy:
  cloudrun:
    projectid: m2c-demo
    region: us-central1