apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: promo-evaluator
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/m2c-demo/container/promo-evaluator
      docker:
        dockerfile: Dockerfile
  googleCloudBuild: {}
    
manifests:
  rawYaml:
    - k8s/deploy.yml
