spring:
  cloud:  
    gcp:
      project-id: m2c-demo
      pubsub:
        credentials: 
          # location: file:/service-key/promo-evaluator.json
          location: classpath:promo-evaluator.json
