apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: promo-evaluator
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/m2c-demo/container/promo-evaluator
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: latest
              name: mongodb-dev
